on:
  issue_comment:
    types: [created, updated, deleted]

jobs:
  reactions:
    name: "Log-reactions"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          REACTIONS: ${{ github.event.issue.reactions }}
